image: djammadev/djamminux:latest

stages:
  - install
  - test
  - build
  - deploy
  - merge-request
  - tag

install react-lib:
  artifacts:
    paths:
      - node_modules/
  stage: install
  tags:
    - dd-runner
  script:
    - npm install
  only:
    changes:
      - src/**/*
      - package.json
      - .gitlab-ci.yml
  except:
    - tags

test react-lib:
  stage: test
  tags:
    - dd-runner
  script:
    - npm run test
  only:
    changes:
      - src/**/*
      - package.json
      - .gitlab-ci.yml
  except:
    - tags

build react-lib:
  artifacts:
    paths:
      - dist/
  stage: build
  tags:
    - dd-runner
  script:
    - npm run build
  only:
    changes:
      - src/**/*
      - package.json
      - .gitlab-ci.yml
  except:
    - tags

open merge request on develop:
  stage: merge-request
  tags:
    - dd-runner
  script:
    - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${PRIVATE_TOKEN} gitlabci.sh create_merge --target-branch develop --remove-source-branch
  except:
    - develop
    - master
    - /^develop_.*$/
    - /^master_.*$/
    - tags

opening merge request on features:
  stage: merge-request
  tags:
    - dd-runner
  script:
    - args=(`echo $(echo $CI_COMMIT_REF_NAME | tr _ "\n")`)
    - ALIAS=$args
    - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${PRIVATE_TOKEN}  gitlabci.sh create_merge --target-branch ${ALIAS} --remove-source-branch --merge-when-pipelines-succeeds
  only:
    - /^develop_.*$/
    - /^master_.*$/

opening merge request develop on master:
  stage: merge-request
  tags:
    - dd-runner
  script:
    - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${PRIVATE_TOKEN} gitlabci.sh create_merge --target-branch master
  only:
    - develop
  when: manual

# Master - NPM
deploy react-lib on npm:
  stage: deploy
  tags:
    - dd-runner
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}">.npmrc
    - NPM_TOKEN=${NPM_TOKEN} npm publish --access public
  only:
    changes:
      - src/**/*
      - .gitlab-ci.yml
    refs:
      - master

tagging build:
  stage: tag
  tags:
    - dd-runner
  script:
    - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${PRIVATE_TOKEN}  gitlabci.sh create_tag -T build -t ${CI_COMMIT_REF_NAME}
  only:
    changes:
      - src/**/*
    refs:
      - master
      - develop
